In [1]:
from SurvSet.data import SurvLoader

In [82]:
import pandas as pd

In [2]:
loader = SurvLoader()

In [58]:
df = loader.df_ds[loader.df_ds.is_td]

In [59]:
df

            ds  is_td     n  n_fac  n_ohe  n_num
11   epileptic   True  1286      3      3      2
28       heart   True   172      2      2      2
58  heartvalve   True   984     12     16      7
59       Rossi   True  1405      8     26      1
63         csl   True  2481      2      2      4
65        aids   True  1405      4      4      1
69     oldmort   True  6495      5     11      2

In [76]:
df, ref = loader.load_dataset(ds_name='Rossi').values()

In [77]:
len(df)

1405

In [78]:
df.head()

,pid,event,time,time2,num_age,fac_fin,fac_race,fac_wexp,fac_mar,fac_paro,fac_prio,fac_educ,fac_emp
0,1,1,0,20,27,no,black,no,not married,yes,3,3,0
1,2,0,0,9,18,no,black,no,not married,yes,8,4,0
2,2,0,9,14,18,no,black,no,not married,yes,8,4,1
3,2,1,14,17,18,no,black,no,not married,yes,8,4,0
4,3,0,0,16,19,no,other,yes,not married,yes,13,3,0

In [79]:
groups = df.groupby('pid').agg({'pid':'count'})

In [80]:
groups.pid.max()

10

In [81]:
len(groups)

432

In [83]:
path = '/Users/mariana/Documents/projects/Huawei/SurvanData/kkbox-churn-prediction-challenge/data/churn_comp_refresh/user_logs_v2.csv'
df = pd.read_csv(path)

In [85]:
df.columns

Index(['msno', 'date', 'num_25', 'num_50', 'num_75', 'num_985', 'num_100',
       'num_unq', 'total_secs'],
      dtype='object')

In [92]:
delta_counts = df.groupby('msno').agg({'num_50': 'count'})

In [93]:
len(delta_counts)

1103894

In [103]:
delta_counts.num_50.head()

msno
+++IZseRRiQS9aaSkH6cMYU6bGDcxUieAi/tH67sC5s=    26
+++hVY1rZox/33YtvDgmKA2Frg/2qhkz12B9ylCvh8o=    31
+++l/EXNMLTijfLBa8p2TUVVVp2aFGSuUI/h7mLmthw=    28
+++snpr7pmobhLKUgSHTv/mpkqgBT0tQJ0zQj6qKrqc=    21
++/9R3sX37CjxbY/AaGvbwr3QkwElKBCtSvVzhCBDOk=    29
Name: num_50, dtype: int64

In [104]:
df.columns

Index(['msno', 'date', 'num_25', 'num_50', 'num_75', 'num_985', 'num_100',
       'num_unq', 'total_secs'],
      dtype='object')